### PR TITLE
Refactor map and camera setup to ECSScene class

### LINKED ISSUE #13: Move Tile Map Setup Code into new Method
We have code for setting up a tile map and the camera inside `src/scenes/hacking-scene.js`. When we make more levels, we don't want to duplicate this code, so we should move into into one function into a super class of every level.

1. Find the super class of the `HackingScene`. It should be called `ECSScene`
2. Make a new method called "setupMapAndCamera"
3. Copy the code at the beginning of the `HackingScene`'s create function to this method.
4. Replace any reference to "SuperMarioBros-World1-1", "mario-tiles", or "World1" with an appropriate method argument.
5. Replace the code at the beginning of the `HackingScene`'s create function with a call to this method.

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

Fixes #13 

Hi there! I came across this issue and although it was in "In Progress", it didn't look like anyone was working on it, so I thought I'd take a shot at a fix. The only thing I wasn't certain of was whether the world and camera bounds would be likely to be different for different scenes. (It seemed like the answer was no, but if not let me know and I can adjust the PR!)

### CODE REVIEW

**Comment by Tass0sm** [comment]
This is good work and worth merging. Unfortunately, this is a learning project for students in the Code4Community club at OSU, and a student is working on this issue in the MapSetup branch. Good luck on your future open source work!

**Comment by jayeclark** [comment]
Please consider adding clear information to that effect in your readme and getting started guides.

**Comment by Tass0sm** [comment]
I have now merged this into the MapSetup branch.

**Comment by jayeclark** [comment]
Thanks, I appreciate the merge and hope my suggestions are helpful to whoever is working on the issue. 

In case my last message came across the wrong way, it's perfectly fine to have an open source project be restricted to certain types of contributors, and I certainly don't want to step on any toes or take away someone's learning opportunity. 

I should have reached out to verify that the In Progress tag meant someone was still actively working on the issue even though no one was assigned. However, a line in the readme also would be very helpful in discouraging random non-OSU contributions.

**Pull request closed without merging**
